language: scala
scala:
  - 2.12.4
  - 2.11.11
  - 2.10.6
jdk:
  - oraclejdk8

branches:
  only: master

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
