language: scala
scala:
  - 2.12.4
  - 2.13.0-M2
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk8

branches:
  only: master

script:
  - scripts/travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
